#!/bin/bash

# Exit on error
set -e

# Declare constants
TIMER="btrfs-snp.timer"
SERVICE="btrfs-snp.service"

# Verify unit files
# systemd-analyze verify "/etc/systemd/system/${TIMER}"
# systemd-analyze verify "/etc/systemd/system/${SERVICE}"

systemctl start  "$TIMER"
systemctl enable "$TIMER"
